spring:
  profiles:
    active: dev
---
server:
  port: 8201
spring:
  profiles:  dev   #开发环境
  application:
      name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatisCfg.xml
  type-aliases-package: com.test.demo.dto
  mapper-locations: classpath:mybatis/mapper/**/*.xml              
spring:
   profiles:  provider   
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource           
    driver-class-name: com.mysql.cj.jdbc.Driver             
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf8 
    username: root
    password: root


info:
  app.name: hand-springboot
  company.name: www.baidu.com
  build.id: $project.artifactId$
  bulid.version: $project.version$